<?php

namespace AppBundle\Repository;

/**
 * CustomerOrderStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
