<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Customer;
use AppBundle\Entity\CustomerAddress;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Customer $customer
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function anonymize(Customer $customer)
    {
        $em = $this->getEntityManager();

        $customer->setName('***');
        $customer->setSurname('***');
        $customer->setEmail(sha1($customer->getId() . $customer->getEmail()));
        $customer->setPhone(sha1($customer->getId() . $customer->getPhone()));
        $customer->setAnonymized(true);
        $customer->setAnonymizedAt(new \DateTime());
        $em->persist($customer);
        /** @var CustomerAddress $address */
        foreach($customer->getAddresses() as $address) {
            $address->setCity('***');
            $address->setStreetAddress('***');
            $address->setFloor(-1);
            $address->setNotes('***');
            $em->persist($address);
        }

        $em->flush();
    }
}
