<?php

namespace AppBundle\Repository;

/**
 * ProcessLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessLogRepository extends \Doctrine\ORM\EntityRepository
{
}
